export const LECCIONES=[
   {numero:1, nombre:'1 Lectura precisa'},
   {numero:2, nombre:'2 Articulación clara'},
   {numero:3, nombre:'3 Pronunciación correcta'},
   {numero:5, nombre:'5 Uso adecuado de las pausas'},
   {numero:6, nombre:'6 Énfasis acertado'},
   {numero:7, nombre:'7 Énfasis en las ideas principales'},
   {numero:8, nombre:'8 Volumen adecuado'},
  {numero:9, nombre:' 9 Modulación'},
  {numero:10, nombre:'10 Entusiasmo'},
  {numero:11, nombre:'11 Afecto y otros sentimientos'},
  {numero:12, nombre:'12 Ademanes y expresiones faciales'},
  {numero:13, nombre:'13 Contacto visual'},
  {numero:14, nombre:'14 Naturalidad'},
  {numero:15, nombre:'15 Buena apariencia'},
  {numero:16, nombre:'16 Aplomo'},
  {numero:17, nombre:'17 Buen uso del micrófono'},
  {numero:18, nombre:'18 Uso de la Biblia para contestar preguntas'},
  {numero:19, nombre:'19 Animar a emplear la Biblia'},
  {numero:20, nombre:'20 Introducción eficaz a los textos bíblicos'},
  {numero:21, nombre:'21 Lectura de textos bíblicos con el énfasis debido'},
  {numero:22, nombre:'22 Empleo correcto de los textos bíblicos'},
  {numero:23, nombre:'23 Resaltar el valor práctico'},
  {numero:24, nombre:'24 Buen uso del vocabulario'},
  {numero:25, nombre:'25 Uso de un bosquejo'},
  {numero:26, nombre:'26 Desarrollo lógico de la información'},
  {numero:27, nombre:'27 Improvisar las palabras a partir del bosquejo'},
  {numero:28, nombre:'28 Tono conversacional'},
  {numero:29, nombre:'29 Calidad de la voz'},
  {numero:30, nombre:'30 Interés en los oyentes'},
  {numero:31, nombre:'31 Respeto a los demás'},
  {numero:32, nombre:'32 Expresarse con convicción'},
  {numero:33, nombre:'33 Hablar con tacto, pero con firmeza'},
  {numero:34, nombre:'34 Ser edificante y positivo'},
  {numero:35, nombre:'35 Repetición para dar énfasis'},
  {numero:36, nombre:'36 Desarrollo del tema'},
  {numero:37, nombre:'37 Destacar los puntos principales'},
  {numero:38, nombre:'38 Introducciones que despiertan interés'},
  {numero:39, nombre:'39 Conclusiones eficaces'},
  {numero:40, nombre:'40 Exactitud en las afirmaciones'},
  {numero:41, nombre:'41 Claridad en la exposición'},
  {numero:42, nombre:'42 Exposición instructiva para el auditorio'},
  {numero:43, nombre:'43 Utilizar la información asignada'},
  {numero:44, nombre:'44 Uso eficaz de las preguntas'},
  {numero:45, nombre:'45 Ilustraciones instructivas'},
  {numero:46, nombre:'46 Ilustraciones basadas en situaciones conocidas'},
  {numero:47, nombre:'47 Uso eficaz de medios visuales'},
  {numero:48, nombre:'48 Argumentación que induce a razonar'},
  {numero:49, nombre:'49 Solidez en la argumentación'},
  {numero:50, nombre:'50 Llegar al corazón'},
  {numero:51, nombre:'51 Atenerse al tiempo y distribuirlo bien'},
  {numero:52, nombre:'52 Exhortación eficaz'},
  {numero:53, nombre:'53 Animar y fortalecer al auditorio'},
];
